#include <nuttx/config.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <unistd.h>
#include <pthread.h>
#include <dirent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <time.h>
#include <syslog.h>

#define MAX_PATH 100
#define DEFAULT_STACKSIZE 8192
#define TASK_PRIORITY SCHED_PRIORITY_DEFAULT
#define TEST_dir "stab_test_dir"
#define TEST_FILE "testfile"
#define TEST_FILE_MAX_SIZE 64 * 1024
#define THREAD_1 "thread_1"
#define THREAD_2 "thread_2"
#define THREAD_3 "thread_3"

/****************************************************************************
 * Name: test01
 * Usage: CMD [-d  path] [-t time(minutes)]
 * Example description:
 	1. Main creates a testfile" testfile"
    2. The main program creates and initializes three threads named thread_1, thread_2, and thread_3.
    The steps of thread_1:
        (1) : Open the test file and write 1K of data.File open mode "A +"
        (2) : Close the test file
        (3) : Check whether the file size exceeds the specified value.TEST_FILE_MAX_SIZE 64 * 1024).Exceeding this value clears the file contents.
        (4) : Repeat the above steps
    Thread_2 steps:
        (1) Repeatedly create and write a test file, and the file name is randomly generated.
    The steps of THREAD_3:
        (1) Loop read test files generated by thread_1.Read 10 bytes at a time.
        (2) A mutex is added when a thread reads and writes a file. Thread_1 & Thread_2 access the same file
    3. Verify test results
    4. Clean up the test environment and exit
 * Expect results: TEST PASSED
 ****************************************************************************/

static pthread_mutex_t mutex;
static int test_flag = 0;
static char test_path[64] = {0};
static int test_time = 24;
static FILE *test_fp = NULL;
static int pthread1_exit = 0;
static int pthread2_exit = 0;
static int pthread3_exit = 0;

struct threadpara
{
    int thread_id;
    char *thread_name;
    char *filename;
};

static void rm_test_dir(char *path)
{
    FAR DIR *dir = opendir(path);
    while (1)
    {
        char fullpath[MAX_PATH];
        struct dirent *ent = readdir(dir);
        if (ent == NULL)
        {
            closedir(dir);
            rmdir(path);
            break;
        }
        int ret = snprintf(fullpath, MAX_PATH, "%s/%s", path, ent->d_name);
        if (ret < 0)
        {
            syslog(LOG_ERR, "snprintf fail\n");
            exit(EXIT_FAILURE);
        }
        if (ent->d_type == 2)
        {
            rm_test_dir(fullpath);
        }
        else
        {
            unlink(fullpath);
        }
    }
}

static void cleanup(void)
{
    char buf[MAX_PATH] = {0};
    getcwd(buf, sizeof(buf));
    rm_test_dir(buf);
}

static void result_check(int ret)
{
    syslog(LOG_INFO, "test completed......\n");
    ret > 0 ? syslog(LOG_ERR, "TEST FAILED !\n") : syslog(LOG_INFO, "TEST PASSED !\n");
}

/****************************************************************************
 * Name: get_test_file_name
 *
 * Description:
 *   A random string is generated as a file name for testing
 *
 * Returned Value:
 *   fail      NULL
 *   success   (string) file name
 ****************************************************************************/
static char *get_test_file_name(int length)
{
    int flag, i;
    char *string;
    srand((unsigned int)(time((time_t *)NULL) + length));
    if ((string = (char *)malloc(length + 1)) == NULL)
    {
        syslog(LOG_ERR, "Malloc failed!\n");
        return NULL;
    }
    for (i = 0; i < length; i++)
    {
        flag = rand() % 4;
        switch (flag)
        {
        case 0:
            string[i] = 'A' + rand() % 26;
            break;
        case 1:
            string[i] = 'a' + rand() % 26;
            break;
        case 2:
            string[i] = '0' + rand() % 10;
            break;
        case 3:
            string[i] = '#' + rand() % 3;
            break;
        default:
            string[i] = 'x';
            break;
        }
    }
    string[length] = '\0';
    return string;
}

/****************************************************************************
 * The worker thread_1
 ****************************************************************************/
static void *thread_funtion_1(void *arg)
{
    int rval;
    char str[1024] = {0};

    while (1)
    {
        if (pthread1_exit > 0)
        {
            test_flag += 0;
            pthread_exit(NULL);
        }

        memset(str, 'A', sizeof(str));
        syslog(LOG_INFO, "[%s] open the test file with 'a+'.\n", THREAD_1);
        pthread_mutex_lock(&mutex);
        fseek(test_fp, 0, SEEK_END);
        syslog(LOG_INFO, "[%s] write file ...\n", THREAD_1);
        rval = fwrite(str, 1, sizeof(str), test_fp);
        fflush(test_fp);
        fsync(fileno(test_fp));
        if (rval == 0)
        {
            syslog(LOG_ERR, "[%s] ERROR : write file fail !\n", THREAD_1);
            test_flag += 4;
            pthread_mutex_unlock(&mutex);
            pthread_exit(NULL);
        }
        syslog(LOG_INFO, "[%s] close the file ...\n", THREAD_1);
        syslog(LOG_INFO, "[%s] the current file size=%ld byte ...\n", THREAD_1, ftell(test_fp));
        if (ftell(test_fp) > 4 * 1024)
        {
            syslog(LOG_INFO, "[%s] The test file exceeds the specified size, Redirect the file pointer position\n", THREAD_1);
            // rewind(test_fp);
            ftruncate(fileno(test_fp), 1);
            fseek(test_fp, 0, SEEK_END);
        }
        pthread_mutex_unlock(&mutex);
        sleep(5);
    }
    test_flag += 0;
    return 0;
}

/****************************************************************************
 * The worker thread_2
 ****************************************************************************/
static void *thread_funtion_2(void *arg)
{
    int rval, fd;
    char buffer[512] = {0};
    char *testFileName = NULL;
    while (1)
    {
        if (pthread2_exit > 0)
        {
            test_flag += 0;
            pthread_exit(NULL);
        }
        testFileName = get_test_file_name(15);
        syslog(LOG_INFO, "[%s] A file name is randomly generated, name=%s .\n", THREAD_2, testFileName);
        syslog(LOG_INFO, "[%s] Use this name to create a file.\n", THREAD_2);
        fd = open(testFileName, O_WRONLY | O_CREAT, 0700);
        if (fd >= 0)
        {
            syslog(LOG_INFO, "[%s] create file success !\n", THREAD_2);
        }
        else
        {
            syslog(LOG_ERR, "[%s] ERROR : create file %s  fail !\n", THREAD_2, testFileName);
            test_flag += 2;
            free(testFileName);
            pthread_exit(NULL);
        }
        syslog(LOG_INFO, "[%s] Write to this file !\n", THREAD_2);
        memset(buffer, '#', sizeof(buffer));
        rval = write(fd, buffer, sizeof(buffer));
        if (rval == -1)
        {
            syslog(LOG_ERR, "[%s] ERROR : write file fail !\n", THREAD_2);
            test_flag += 2;
            free(testFileName);
            close(fd);
            pthread_exit(NULL);
        }
        else
        {
            syslog(LOG_INFO, "[%s] write file success !\n", THREAD_2);
        }
        syslog(LOG_INFO, "[%s] close this file !\n", THREAD_2);
        close(fd);
        sleep(3);
        syslog(LOG_INFO, "[%s] delete file ...\n", THREAD_2);
        rval = remove(testFileName);
        if (rval == -1)
        {
            syslog(LOG_ERR, "[%s] ERROR : remove file %s  fail !\n", THREAD_2, testFileName);
            test_flag += 2;
            free(testFileName);
            break;
        }
        free(testFileName);
        sleep(7);
    }

    test_flag += 0;
    return 0;
}

/****************************************************************************
 * The worker thread_3
 ****************************************************************************/
static void *thread_funtion_3(void *arg)
{
    char buf[10] = {0};
    while (1)
    {
        sleep(2);
        if (pthread3_exit > 0)
        {
            test_flag += 0;
            pthread_exit(NULL);
        }
        syslog(LOG_INFO, "[%s] open the test file...\n", THREAD_3);
        syslog(LOG_INFO, "[%s] Move the pointer to the end of the file...\n", THREAD_3);
        pthread_mutex_lock(&mutex);
        if (ftell(test_fp) > 10)
        {
            if (fseek(test_fp, -10, SEEK_END) < 0)
            {
                syslog(LOG_INFO, "[%s] fseek fail\n", THREAD_3);
                test_flag += 1;
                pthread_mutex_unlock(&mutex);
                break;
            }
        }
        if (ftell(test_fp) == 0)
        {
            syslog(LOG_INFO, "[%s] file is empty...\n", THREAD_3);
        }
        else
        {
            fgets(buf, sizeof(buf), test_fp);
            syslog(LOG_INFO, "[%s] read data from the test file... \n", THREAD_3);
        }
        pthread_mutex_unlock(&mutex);
    }
    test_flag += 0;
    return 0;
}

/****************************************************************************
 * do test
 ****************************************************************************/
static void do_test(void)
{
    time_t start, finish;
    test_flag = 0;
    int status;
    pthread_t thread1, thread2, thread3;
    pthread_attr_t attr;
    pthread_mutex_init(&mutex, NULL);
    status = pthread_attr_init(&attr);
    if (status != 0)
    {
        syslog(LOG_ERR, "[main_process] pthread_test  pthread_attr_init failed, status=%d\n", status);
        test_flag = 1;
        return;
    }
    status = pthread_attr_setstacksize(&attr, DEFAULT_STACKSIZE);
    if (status != 0)
    {
        syslog(LOG_ERR, "[main_process] pthread_test, pthread_attr_setstacksize failed, status=%d\n", status);
        test_flag = 1;
        return;
    }

    if ((test_fp = fopen(TEST_FILE, "a+")) == NULL)
    {
        syslog(LOG_ERR, "[main_process] create file fail !\n");
        test_flag = 1;
        return;
    }

    status = pthread_create(&thread1, &attr, thread_funtion_1, NULL);
    if (status != 0)
    {
        syslog(LOG_ERR, "[main_process] pthread_test  pthread_create failed, status=%d\n", status);
        test_flag = 1;
        return;
    }
    else
    {
        syslog(LOG_INFO, "[main_process] creat thread success !  name=%s\n", THREAD_1);
    }
    status = pthread_create(&thread2, &attr, thread_funtion_2, NULL);
    if (status != 0)
    {
        syslog(LOG_ERR, "[main_process] pthread_test, pthread_create failed, status=%d\n", status);
        test_flag = 1;
        return;
    }
    else
    {
        syslog(LOG_INFO, "[main_process] creat thread success !  name=%s\n", THREAD_2);
    }
    status = pthread_create(&thread3, &attr, thread_funtion_3, NULL);
    if (status != 0)
    {
        syslog(LOG_ERR, "[main_process] pthread_test, pthread_create failed, status=%d\n", status);
        test_flag = 1;
        return;
    }
    else
    {
        syslog(LOG_INFO, "[main_process] creat thread success !  name=%s\n", THREAD_3);
    }
    pthread1_exit = 0;
    pthread2_exit = 0;
    pthread3_exit = 0;
    time(&start);
    while (1)
    {
        time(&finish);
        if ((finish - start) > test_time * 60)
        {
            pthread1_exit = 1;
            pthread2_exit = 1;
            pthread3_exit = 1;
            syslog(LOG_INFO, "[main_process] Exiting the child thread ... ...\n");
            sleep(2);
            break;
        }
        sleep(10);
    }
    switch (test_flag)
    {
    case 0:
        syslog(LOG_INFO, "[main_process] All threads performed successfully and exited normally\n");
        break;
    case 1:
        syslog(LOG_ERR, "[main_process] The thread_3 failed to execute and exited\n");
        break;
    case 2:
        syslog(LOG_ERR, "[main_process] The thread_2 failed to execute and exited\n");
        break;
    case 3:
        syslog(LOG_ERR, "[main_process] The thread_2 & thread_3 failed to execute and exited\n");
        break;
    case 4:
        syslog(LOG_ERR, "[main_process] The thread_1 failed to execute and exited\n");
        break;
    case 5:
        syslog(LOG_ERR, "[main_process] The thread_1 & thread_3 failed to execute and exited\n");
        break;
    case 6:
        syslog(LOG_ERR, "[main_process] The thread_1 & thread_2 failed to execute and exited\n");
        break;
    case 7:
        syslog(LOG_ERR, "[main_process] The thread_1 & thread_2 & thread_3 failed to execute and exited\n");
        break;
    default:
        break;
    }

    fclose(test_fp);
    return;
}

/****************************************************************************
 * Test preparation
 ****************************************************************************/
static void set(int argc, char *argv[])
{
    int status;
    if (argc == 5)
    {
        if (strcmp("-d", argv[1]) == 0)
        {
            if (strncpy(test_path, argv[2], sizeof(test_path) - 1) == NULL)
            {
                syslog(LOG_ERR, "ERROR : strncpy failed !\n");
                exit(EXIT_FAILURE);
            }
        }
        if (strcmp("-t", argv[3]) == 0)
            test_time = atoi(argv[4]);
    }
    else
    {
        syslog(LOG_WARNING, "The argument is wrong !\n");
        syslog(LOG_WARNING, "usage   CMD [-d  path] [-t time(minutes)] !\n");
        exit(1);
    }
    strcat(test_path, "/");
    strcat(test_path, TEST_dir);

    rm_test_dir(test_path);
    status = mkdir(test_path, 0700);
    if (status != 0)
    {
        syslog(LOG_ERR, "[main_process] ERROR : mkdir failed !\n");
        exit(EXIT_FAILURE);
    }
    else
    {
        syslog(LOG_INFO, "[main_process] creat a dir, name=%s\n", test_path);
        chdir(test_path);
    }
    return;
}

/****************************************************************************
 * main
 ****************************************************************************/
int main(int argc, FAR char *argv[])
{
    set(argc, argv);
    do_test();
    cleanup();
    result_check(test_flag);
    exit(test_flag);
}
